### ISSUE TITLE
podnews daily no longer supports 'json' transcript?

### ISSUE THREAD

**Issue by tonytamsf** [jamescridland/podnews#2]
@jamescridland - it looks like podnews daily no longer has json as a transcript format and only WebVTT.  In our previous discussion in an AntennaPod [issue](https://github.com/AntennaPod/AntennaPod/issues/4935), we talked about json and SRT as being good enough.    Do you suggest I work on WebVTT support as well for AntennaPod?

**Comment by jamescridland** [comment]
Hello! I think it was quite some time when we last spoke. 

While I can produce multiple transcripts, I can only manually correct one - and took the decision to only support VTT. 

Unlike SRT, VTT allows for speaker identification, and unlike SRT, it is natively supported by web browsers - if you press the play button on https://podnews.net/listen you’ll find full captioning. 

Additionally, Apple Podcasts supports it (including speaker identification , importantly), and as far as I can see prefers it over other formats.

Hmm - probably best to add it?

**Comment by tonytamsf** [comment]
Thanks for the explanation.  I will add support for VTT in AntennaPod.

**Comment by tonytamsf** [comment]
FYI: open issue on AntennaPod https://github.com/AntennaPod/AntennaPod/issues/7431
